PDFC = pdflatex
#BC = bibtex

All:
	${PDFC} A_First_Course_In_Turbulence.tex
	#${BC} A_First_Couse_In_Turbulence.aux
	${PDFC} A_First_Course_In_Turbulence.tex
	${PDFC} A_First_Course_In_Turbulence.tex

clean:
	-rm -f *.pdf *.dvi
	-rm -f A_First_Course_In_Turbulence.bbl A_First_Course_In_Turbulence.blg A_First_Course_In_Turbulence.log A_First_Course_In_Turbulence.out A_First_Course_In_Turbulence.spl A_First_Course_In_Turbulence.aux


